export const CONFIG = {
    ACTOR_LAYER_LENGTHS: [256, 256, 256],
    CRITIC_LAYER_LENGTHS: [256, 256, 256],

    GAME_STATE_SIZE: 27,
    ACTION_SIZE: 5,

    LEARNING_RATE_ACTOR: 0.0003,
    LEARNING_RATE_CRITIC: 0.0005,

    WARM_UP_EPISODES: 10,
    SAVE_AFTER_EPISODES: 800,
    MAX_SAVED_MODELS: 20,
    SWITCH_OPPONENT_EVERY_EPISODES: 100,
    DISCOUNT_FACTOR: 0.992,
    LAMBDA: 0.975,
    EPOCHS: 6,
    ROLLOUT_EPISODES: 10,

    ENTROPY_COEFFICIENT: 0.05,
    ENTROPY_DECAY: 0.999,
    MIN_ENTROPY: 0.025,

    CLIP: 0.2,

    USE_LAYER_NORM: true,

    ELO_K: 24,
    ELO_DIFF_SCALE: 200,

    PLAYER_ONE_ID: 200,
    PLAYER_TWO_ID: 201,
    POSITION_NORMALIZATION: 1 / 500,
    VELOCITY_NORMALIZATION: 3,

    // runtime params
    steps: 0,
    episodes: 0,
};

export function updateConfig(newConfig) {
    Object.assign(CONFIG, newConfig);
}

top.CONFIG = CONFIG;